<?php
// Do not edit this file. Generated by admin script.
// CCK Entity Configuration file
// General Informations 
$cck_entity_configuration_5['check_access_instances']='';
$cck_entity_configuration_5['check_access_fields']='';
$cck_entity_configuration_5['check_access_categories']='';
$cck_entity_configuration_5['max_product_download']='';
$cck_entity_configuration_5['days_for_product_download']='';
?>