<?php
if (!defined('_VALID_MOS') && !defined('_JEXEC')) die('Direct Access to ' . basename(__FILE__) . ' is not allowed.');
/**
* @package OS CCK
* @copyright 2019 OrdaSoft.
* @author Andrey Kvasnevskiy(akbet@mail.ru),Roman Akoev (akoevroman@gmail.com)
* @link http://ordasoft.com/cck-content-construction-kit-for-joomla.html
* @description OrdaSoft Content Construction Kit
* @license GNU General Public license version 2 or later; 
*/

// Do not edit this file. Generated by admin script.
// CCK Entity Configuration file
// General Informations 
$cck_entity_configuration_default['check_access_instances']='0';
$cck_entity_configuration_default['check_access_fields']='0';
$cck_entity_configuration_default['check_access_categories']='0';
$cck_entity_configuration_default['max_product_download']='0';
$cck_entity_configuration_default['days_for_product_download']='0';
?>